[package]
name = "millegrilles_core"
version = "2026.0.120"
edition = "2024"

[dependencies]
millegrilles_common_rust = { git = "https://github.com/dugrema/millegrilles_common_rust.git", tag = "2026.0-release1" }
# millegrilles_common_rust = { git = "https://github.com/dugrema/millegrilles_common_rust.git", branch = "master" }
# millegrilles_common_rust = { git = "https://github.com/dugrema/millegrilles_common_rust.git", branch = "update20260410" }
# millegrilles_common_rust = { path = "/home/mathieu/RustroverProjects/millegrilles_common_rust" }

log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_info"] }
env_logger = "0.11.10"
serde = { version = "1.0.228", features = ["derive"] }
webauthn-rs = { "version" = "0.4.8", "features" = ["danger-allow-state-serialisation"] }
totp-rs = { "version" = "5.7.1", features = ["default", "gen_secret", "qr", "serde_support", "zeroize"] }
